name: Improvability_Score CI/CD

on:
  push:
    branches:
      - main  # Modify this branch name to match your repository's main branch

jobs:
  build:
    runs-on: windows-latest  # You can choose a different runner as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.6  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Replace with your project's requirements file if needed

    - name: Run tests
      run: |
        python -m pytest  # Replace with your test command

    - name: Deploy to Production
      if: success()
      run: |
        runas /user:Administrator streamlit run main.py -- --global.developmentMode --logger.level=debug
